print('Enter three seperate numbers')
print('Enter your first number')
x=float(input())
print('Enter your second number')
y=float(input())
print('Enter your third number')
z=float(input())
t = [x, y, z]
t.sort()
print(t,'is sorted least to greatest')
